"""init

Revision ID: 2cb2b847d3fb
Revises: 
Create Date: 2023-06-22 22:26:54.969193

"""
from alembic import op
import clickhouse_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb2b847d3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE DATABASE IF NOT EXISTS default')
    op.execute('CREATE DATABASE IF NOT EXISTS {{ OARS_XAPI_DATABASE }}')
    op.execute('CREATE DATABASE IF NOT EXISTS {{ OARS_EVENT_SINK_DATABASE }}')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP DATABASE IF EXISTS default')
    op.execute('DROP DATABASE IF EXISTS {{ OARS_XAPI_DATABASE }}')
    op.execute('DROP DATABASE IF EXISTS {{ OARS_EVENT_SINK_DATABASE }}')
    # ### end Alembic commands ###
