[tox]
envlist = lint, format
requires = tox-uv>=1

[testenv:lint]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pylint src/tutoraspects

[testenv:format]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    black --check --exclude templates src/tutoraspects
    sqlfmt src/tutoraspects/templates/openedx-assets/queries --check
