name: Tutor Integration Test

on:
  pull_request:
    paths-ignore:
      - .github/**
      - .ci/**
      - .gitignore
      - CHANGELOG.md
      - setup.cfg
      - tutoraspects/__about__.py

env:
  TUTOR_ROOT: ./.ci/

jobs:
  compose:
    name: ${{ matrix.mode }} (${{ matrix.xapi }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [local, dev]
        xapi: [ralph, vector]
        include:
          - mode: local
            image: openedx
          - mode: dev
            image: openedx-dev
          - performance_metrics: full # runs unfiltered all charts
          - mode: local
            xapi: vector
            performance_metrics: filtered # runs charts with specific org & course
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Aspects
        uses: ./.github/actions/aspects-setup
        with:
          xapi_source: ${{ matrix.xapi }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tutor build images
        run: tutor images build ${{ matrix.image }} aspects aspects-superset permissions
      - name: Tutor start + init
        uses: ./.github/actions/tutor-init-cached
        with:
          mode: ${{ matrix.mode }}
      - name: Run the Aspects test suite
        uses: ./.github/actions/aspects-test-suite
        with:
          mode: ${{ matrix.mode }}
          performance_metrics: ${{ matrix.performance_metrics }}
      - name: Tutor stop
        run: tutor ${{ matrix.mode }} stop

  k8s:
    name: k8s (${{ matrix.xapi }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        xapi: [ralph, vector]
        include:
          - xapi: ralph
            performance_metrics: full
          - xapi: vector
            performance_metrics: full
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Aspects
        uses: ./.github/actions/aspects-setup
        with:
          xapi_source: ${{ matrix.xapi }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Arkade
        uses: alexellis/setup-arkade@607b18a33318c973136b241de1a95c46b84698f4 # v4
      - name: Run Kubernetes tools
        uses: alexellis/arkade-get@5594ddff52ec7b8a71efd73acaa9e52936e35e16 # Aug.22.26 - repo has zero tags so master-HEAD SHA is the only option
        with:
          kustomize: v5.8.1
          helm: v3.22.0
          kubeconform: v0.8.0
      - name: Kustomize build
        run: |
            kustomize build $TUTOR_ROOT/env | kubeconform -strict -ignore-missing-schemas -kubernetes-version 1.35.0
      - name: Tutor build images
        run: tutor images build openedx aspects aspects-superset
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
      - name: Mount docker image
        run: |
          kind get clusters
          kind load docker-image $(tutor images printtag openedx) --name chart-testing
          kind load docker-image $(tutor images printtag aspects) --name chart-testing
          kind load docker-image $(tutor images printtag aspects-superset) --name chart-testing
      - name: Setup namespace
        run: |
          kubectl config set-context --current --namespace=openedx
          kubectl get pods
      - name: Init k8s environment
        run: |
          tutor k8s start
          tutor k8s do init
      - name: Run the Aspects test suite
        uses: ./.github/actions/aspects-test-suite
        with:
          mode: k8s
          performance_metrics: ${{ matrix.performance_metrics }}
      - name: Check failure logs
        if: failure()
        run: |
          # Use an array to store pod names
          pod_list=($(kubectl get pods -o jsonpath='{.items[*].metadata.name}'))

          failed_jobs=""

          # Loop through each pod and check for failure
          for pod_name in "${pod_list[@]}"; do
            # Get the pod phase/status
            pod_phase=$(kubectl get pod "$pod_name" -o jsonpath='{.status.phase}')

            if [[ "$pod_phase" != "Running" && "$pod_phase" != "Succeeded" ]]; then
              # Job is not in Running or Succeeded state, consider it as failed
              failed_jobs="$failed_jobs $pod_name"
              # Print the logs for the failing pod
              echo "Failure logs for pod: $pod_name"
              kubectl logs "$pod_name"
            fi
          done

          # Check if any jobs failed
          if [ -n "$failed_jobs" ]; then
            echo "The following jobs failed: $failed_jobs"
          else
            echo "All jobs succeeded."
          fi
      - name: Check service logs
        if: failure()
        run: |
          # Use an array to store service names
          service_list=($(kubectl get services -o jsonpath='{.items[*].metadata.name}'))

          # Loop through each service and print logs
          for service_name in "${service_list[@]}"; do
            echo "Logs for service: $service_name"
            kubectl logs "svc/$service_name"
            echo "------------------------"
          done
      - name: Check jobs logs
        if: "!cancelled()"
        run: |
          job_list=($(kubectl get jobs | grep job | awk '{print $1}'))

          # Function to print logs for a pod
          print_pod_logs() {
            local pod_name="$1"
            echo "Logs for pod: $pod_name"
            kubectl logs "$pod_name"
            echo "------------------------"
          }

          # Loop through each job-related pod and print logs
          for job_name in "${job_list[@]}"; do
            # Get the pods related to the current job
            job_pod_list=($(kubectl get pods | grep -E "${job_name}-.*" | awk '{print $1}'))

            for pod_name in "${job_pod_list[@]}"; do
              print_pod_logs "$pod_name"
            done
          done
